name: Torpedo Software
tagline: Making waves by propelling new technologies
email: zack@boatbomber.com
socials:
  - label: GitHub
    url: https://github.com/torpedosoftware
  - label: Twitter
    url: https://twitter.com/TorpedoSoftware
  - label: LinkedIn
    url: https://www.linkedin.com/company/torpedo-software-llc
  - label: Roblox
    url: https://www.roblox.com/groups/14766364/Torpedo-Software-LLC
